FROM tsl0922/ttyd as ttyd

FROM python:3.10-slim

COPY --from=ttyd /usr/bin/ttyd /usr/bin/ttyd

COPY . /opt/irissqlcli

RUN cd /opt/irissqlcli && pip install -e .

ENV IRIS_HOSTNAME=host.docker.internal
ENV IRIS_PORT=1972
ENV IRIS_NAMESPACE=USER
ENV IRIS_USERNAME=_SYSTEM
ENV IRIS_PASSWORD=SYS

RUN apt update && \
  apt install -y --no-install-recommends tini && \
  rm -rf /var/lib/apt/lists/* && \
  chmod +x /usr/bin/ttyd

EXPOSE 7681

ENTRYPOINT ["/usr/bin/tini", "--", "ttyd"]

CMD ["python", "-m", "irissqlcli"]